server:
  port: 8089
  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password: 20011104
    url: jdbc:mysql://localhost:3306/vue?serverTimezone=GMT%2b8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB  #单个数据大小
      max-request-size: 100MB #总数据大小

# 动态sql扫描
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/Chrome-Edge/IDEA/Vue/Backup--(CodeGenerator)/files/